name: Melvor Idle Example Mod Actions

on:
  push:
    branches:
      - develop

jobs:
  setup-and-build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up files
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Copy Manifest.json
        run: cp manifest.json ./.build/exampleMod/
      - name: Zip mod folder
        run: zip -r exampleMod.zip ./.build/exampleMod
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exampleModZipFile
          path: ./.build/exampleMod.zip
  upload:
    needs: setup-and-build-npm
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: exampleModZipFile
      - name: Upload to mod.io
        uses: nickelc/upload-to-modio@v1
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: 2869
          mod: 2431214
          path: ./.build/exampleMod/modfile.zip
