name: Melvor Idle Example Mod Actions

on:
  push:
    branches:
      - develop

jobs:
  setup-and-build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up files
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Copy Manifest.json
        run: cp manifest.json ./.build/

      - name: Zip mod folder
        run: zip -r ./.build/exampleMod.zip ./.build/

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: exampleModZipFile
          path: ./.build/exampleMod.zip

  upload:
    needs: setup-and-build-npm
    runs-on: ubuntu-latest
    steps:
      - name: Set up files
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: exampleModZipFile
      - name: Extract config data
        id: config
        run: |
          game_id=$(jq '.game' config.json)
          mod_id=$(jq '.mod' config.json)
          version=$(jq '.version' config.json)

          echo "game=${game_id}" >> $GITHUB_OUTPUT
          echo "mod=${mod_id}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Check files
        run: ls
        
      - name: Upload to mod.io
        uses: Durza32/upload-to-modio@v1.9
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: ${{ steps.config.outputs.game }}
          mod: ${{ steps.config.outputs.mod }}
          version: ${{ steps.config.outputs.version }}
          path: ./exampleMod.zip
          active: false
